apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-stack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-stack
  template:
    metadata:
      labels:
        app: health-stack
    spec:
      containers:
        - name: health-container
          image: didin8080/health-stack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred
